### PR TITLE
Create universal wheels

### PR DESCRIPTION
**Pull request by edmorley**
Previously the generated wheel was only for the version of Python under which the `setup.py publish` command was run, which means the Python 3 wheel was missing for the latest release:
https://pypi.python.org/pypi/coreschema/0.0.4

### CODE REVIEW

**Comment by jdufresne** [comment]
After #14 lands, you could include the license file in the generated wheel using the `license_file` in `setup.cfg`:

```ini
[metadata]
license_file = LICENSE
```

See the documentation for information on this feature of wheel:

https://wheel.readthedocs.io/en/stable/#including-the-license-in-the-generated-wheel-file

This would satisfy the license's requirement:

>  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

**Comment by edmorley** [comment]
Hi! That seems orthogonal to this PR? Wheels are already being created; this PR just makes sure they are created for both Python 2 and 3, not just one of Python {2, 3}. 

As such, it's probably best as a new issue (or a comment on #14), rather than here.

**Comment by edmorley** [comment]
@tomchristie, don't suppose you could merge this? :-)

**Comment by edmorley** [comment]
Ping? :-)

**Comment by lovelydinosaur** [comment]
Refs https://github.com/core-api/python-openapi-codec/pull/47

**Pull request closed without merging**
